# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule: # Run workflow automatically
    - cron: '15 23 */2 * 3' # Runs every hour, on the hour
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Install Language - Initial
        run: sudo apt-get install ttf-wqy-microhei ttf-wqy-zenhei chromium-browser chromium-browser-l10n fonts-droid-fallback
      - run: npm install
      - run: node index.js
      - name: Commit report
        run: |
          git add -A
          git config --global user.name 'ShaokangJiang'
          git config --global user.email 'shj002@ucsd.edu'
          git commit -am "update Data"
          git push
